export const actionType = {
    GET_SESSION_REQUEST: 'GET_SESSION_REQUEST',
    GET_SESSION_SUCCESS: 'GET_SESSION_SUCCESS',
    GET_SESSION_FAILED: 'GET_SESSION_FAILED',
  
    LOAD_SECTIONS_REQUEST: 'LOAD_SECTIONS_REQUEST',
    LOAD_SECTIONS_SUCCESS: 'LOAD_SECTIONS_SUCCESS',
    LOAD_SECTIONS_FAILED: 'LOAD_SECTIONS_FAILED',
    ADD_SECTION_SUCCESS: 'ADD_SECTION_SUCCESS',
    ADD_SECTION_REQUEST: 'ADD_SECTION_REQUEST',
    ADD_SECTION_FAILED: 'ADD_SECTION_FAILED'
  };
  
  
  